profile: coverage.out
# Holds regexp rules which will exclude matched files or packages
# from coverage statistics
exclude:
  # Exclude files or packages matching their paths
  paths:
    - \.pb\.go$    # excludes all protobuf generated files