// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.12.4
// source: proto/service/contract/response.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseShort struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ResponseShort) Reset() {
	*x = ResponseShort{}
	mi := &file_proto_service_contract_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseShort) ProtoMessage() {}

func (x *ResponseShort) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_contract_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseShort.ProtoReflect.Descriptor instead.
func (*ResponseShort) Descriptor() ([]byte, []int) {
	return file_proto_service_contract_response_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseShort) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ResponseBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Batch []*Batch `protobuf:"bytes,1,rep,name=batch,proto3" json:"batch,omitempty"`
}

func (x *ResponseBatch) Reset() {
	*x = ResponseBatch{}
	mi := &file_proto_service_contract_response_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBatch) ProtoMessage() {}

func (x *ResponseBatch) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_contract_response_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBatch.ProtoReflect.Descriptor instead.
func (*ResponseBatch) Descriptor() ([]byte, []int) {
	return file_proto_service_contract_response_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseBatch) GetBatch() []*Batch {
	if x != nil {
		return x.Batch
	}
	return nil
}

type ResponseUserUrl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url []*Url `protobuf:"bytes,1,rep,name=url,proto3" json:"url,omitempty"`
}

func (x *ResponseUserUrl) Reset() {
	*x = ResponseUserUrl{}
	mi := &file_proto_service_contract_response_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseUserUrl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUserUrl) ProtoMessage() {}

func (x *ResponseUserUrl) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_contract_response_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUserUrl.ProtoReflect.Descriptor instead.
func (*ResponseUserUrl) Descriptor() ([]byte, []int) {
	return file_proto_service_contract_response_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseUserUrl) GetUrl() []*Url {
	if x != nil {
		return x.Url
	}
	return nil
}

type ResponseStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Urls  int64 `protobuf:"varint,1,opt,name=urls,proto3" json:"urls,omitempty"`
	Users int64 `protobuf:"varint,2,opt,name=users,proto3" json:"users,omitempty"`
}

func (x *ResponseStats) Reset() {
	*x = ResponseStats{}
	mi := &file_proto_service_contract_response_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseStats) ProtoMessage() {}

func (x *ResponseStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_service_contract_response_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseStats.ProtoReflect.Descriptor instead.
func (*ResponseStats) Descriptor() ([]byte, []int) {
	return file_proto_service_contract_response_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseStats) GetUrls() int64 {
	if x != nil {
		return x.Urls
	}
	return 0
}

func (x *ResponseStats) GetUsers() int64 {
	if x != nil {
		return x.Users
	}
	return 0
}

var File_proto_service_contract_response_proto protoreflect.FileDescriptor

var file_proto_service_contract_response_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x1a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23,
	0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x22, 0x3e, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x12, 0x2d, 0x0a, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x52, 0x05, 0x62, 0x61,
	0x74, 0x63, 0x68, 0x22, 0x3a, 0x0a, 0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x27, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x55, 0x72, 0x6c, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22,
	0x39, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x75, 0x72, 0x6c, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x42, 0x43, 0x5a, 0x41, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6f, 0x72, 0x6f, 0x6c, 0x38, 0x34,
	0x38, 0x34, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_service_contract_response_proto_rawDescOnce sync.Once
	file_proto_service_contract_response_proto_rawDescData = file_proto_service_contract_response_proto_rawDesc
)

func file_proto_service_contract_response_proto_rawDescGZIP() []byte {
	file_proto_service_contract_response_proto_rawDescOnce.Do(func() {
		file_proto_service_contract_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_service_contract_response_proto_rawDescData)
	})
	return file_proto_service_contract_response_proto_rawDescData
}

var file_proto_service_contract_response_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_service_contract_response_proto_goTypes = []any{
	(*ResponseShort)(nil),   // 0: service.contract.ResponseShort
	(*ResponseBatch)(nil),   // 1: service.contract.ResponseBatch
	(*ResponseUserUrl)(nil), // 2: service.contract.ResponseUserUrl
	(*ResponseStats)(nil),   // 3: service.contract.ResponseStats
	(*Batch)(nil),           // 4: service.contract.Batch
	(*Url)(nil),             // 5: service.contract.Url
}
var file_proto_service_contract_response_proto_depIdxs = []int32{
	4, // 0: service.contract.ResponseBatch.batch:type_name -> service.contract.Batch
	5, // 1: service.contract.ResponseUserUrl.url:type_name -> service.contract.Url
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_service_contract_response_proto_init() }
func file_proto_service_contract_response_proto_init() {
	if File_proto_service_contract_response_proto != nil {
		return
	}
	file_proto_service_contract_entity_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_service_contract_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_service_contract_response_proto_goTypes,
		DependencyIndexes: file_proto_service_contract_response_proto_depIdxs,
		MessageInfos:      file_proto_service_contract_response_proto_msgTypes,
	}.Build()
	File_proto_service_contract_response_proto = out.File
	file_proto_service_contract_response_proto_rawDesc = nil
	file_proto_service_contract_response_proto_goTypes = nil
	file_proto_service_contract_response_proto_depIdxs = nil
}
